### ISSUE TITLE
benchmarks and status?

### ISSUE THREAD

**Issue by LeanderK** [composewell/fusion-plugin#21]
this plugin looks really interesting! Is it used in practice? Any benchmarks available?

**Comment by pranaysashank** [comment]
I have some benchmarks from Streamly when the plugin was created,
```
| Benchmark Name                                    | Old    | New     |
|---------------------------------------------------+--------+---------|
| readStream/wordcount                              | 1.969s | 308.1ms |
| decode-encode/utf8-arrays                         | 4.159s | 2.952s  |
| decode-encode/utf8                                | 5.708s | 2.117s  |
| splitting/predicate/wordsBy isSpace (word count)  | 2.050s | 311.5ms |
| splitting/long-pattern/splitOnSuffixSeq abc...xyz | 2.558s | 423.3ms |
```
but now all these functions are much faster due to other reasons as well. We have been using it together with Streamly.
@harendra-kumar Any recent benchmarks you have available to share?

**Comment by harendra-kumar** [comment]
For detailed benchmark results see https://github.com/composewell/streamly/pull/387 .

**Comment by harendra-kumar** [comment]
You can run the streamly benchmarks yourself, in the streamly repo:

```
./bench.sh --benchmarks fileio
./bench.sh --benchmarks fileio --cabal-build-flags "--flags fusion-plugin" --append
```

Once this is finished it will produce a comparison of `fileio` benchmarks with and without the plugin, sorted in order of worst to best improvements. You can also run this for other benchmarks suites available in streamly, but `fileio` has been seen to be the one where most improvements are seen

It will also be interesting to see the comparisons after the recent changes in the plugin and using GHC 8.10.

**Comment by harendra-kumar** [comment]
Just realized, by default the fileio benchmark does not include many of the benchmarks improved by fusion-plugin, you also need the `dev` build flag for that, and with that you will also need to supply a big text file to run the benchmarks on.

**Comment by LeanderK** [comment]
looks great! Is the plugin considered experimental or actually used in practice?

**Comment by harendra-kumar** [comment]
It is used in practice, we use it all the time.
