### ISSUE TITLE
Add CI tests for Windows and OSX

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/fusion-plugin#7]
Streamly repo may not be testing the plugin for all OS configs, so it is better to have the CIs in plugin repo itself.

**Comment by harendra-kumar** [comment]
We can just copy the packcheck travis and appveyor config files to this repo and disable the tests that we don't need.

**Comment by pranaysashank** [comment]
Fixed by 1c2b26d7574619d0b28bda84257a0222380978be
